function [visualizationTools] = setupVisualizationTools(sysParamRxObj)
    % setupVisualizationTools: Set up visualization tools (constellation diagram,
    % spectrum analyzer, and time scope) for all BSs using sysParamRxObj.
    %
    % Input:
    %   sysParamRxObj - Structure containing system parameters and receiver objects for each BS
    %
    % Output:
    %   visualizationTools - Structure containing all visualization tools for each BS

    % 初始化保存所有基站可视化工具的结构体
    visualizationTools = struct();

    % 配置工具
    % 获取当前基站的 fieldname (e.g., 'BS_1', 'BS_2')
    current_BS_field = '@UE_1';

    % 从 sysParamRxObj 中提取相关参数
    OFDMParams = sysParamRxObj.OFDMParams;
    dataParams = sysParamRxObj.dataParams;
    
    % 根据基站的modOrder和采样率生成星座图参考点
    refConstHeader = qammod(0:1, 2, UnitAveragePower=true);  % Header is always BPSK
    refConstData   = qammod(0:dataParams.modOrder-1, dataParams.modOrder, UnitAveragePower=true);
    
    % 初始化星座图
    if dataParams.modOrder < 1024
        constDiag = comm.ConstellationDiagram(2, ...
            "ChannelNames", {'Header','Data'}, ...
            "ReferenceConstellation", {refConstHeader, refConstData}, ...
            "ShowLegend", true, ...
            "EnableMeasurements", true, ...
            "MeasurementInterval", 'All displays', ...
            "Title", current_BS_field + " Constellation Diagram");
    else
        constDiag = comm.ConstellationDiagram(2, ...
            "ChannelNames", {'Header','Data'}, ...
            "ReferenceConstellation", {refConstHeader, refConstData}, ...
            "ShowLegend", true, ...
            "ShowReferenceConstellation", false, ...
            "EnableMeasurements", true, ...
            "MeasurementInterval", 'All displays', ...
            "Title", current_BS_field + " Constellation Diagram");
    end
    
    %%%%%%%%%%%%%%%%%%%%%%%%% 这里有一些可选项 %%%%%%%%%%%%%%%%%%%%%%%%%
    constDiag.ShowTrajectory = false;
    %%%%%%%%%%%%%%%%%%%%%%%%% 这里有一些可选项 %%%%%%%%%%%%%%%%%%%%%%%%%
    
    % 初始化频谱分析仪
    spectrumAnalyze = spectrumAnalyzer( ...
        'Name',             'Signal Spectrum', ...
        'Title',            ['(' current_BS_field ') Received Signal '], ...
        'SpectrumType',     'Power', ...
        'FrequencySpan',    'Full', ...
        'SampleRate',       OFDMParams.Subcarrierspacing * OFDMParams.FFTLength, ...
        'ShowLegend',       true, ...
        'ViewType',         'spectrum-and-spectrogram', ...
        'Position',         [100 100 800 500], ...
        'ChannelNames',     {'Received'});
    
    % 初始化时间域图
    timesink = timescope( ...
        'Name',             'Time Scope', ...
        'Title',            ['(' current_BS_field ') Received Signal'], ...
        'ChannelNames',     {'input time-domain data'}, ...
        'ShowLegend',       true, ...
        'SampleRate',       OFDMParams.Subcarrierspacing * OFDMParams.FFTLength, ...
        'YLimits',          [-0.4, 0.4], ...
        'LayoutDimensions', [1, 1], ...
        'ActiveDisplay',    1);

    % 将每个基站的工具保存到结构体中
    visualizationTools.constDiag = constDiag;
    visualizationTools.spectrumAnalyze = spectrumAnalyze;
    visualizationTools.timesink = timesink;
end